# Generated by Django 3.2.8 on 2021-10-09 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
